---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    service:
      name: tomcat
      state: stopped
  - name: Clean the existing war file
    file:
      path: /var/lib/tomcat/webapps/gameoflife.war
      state: absent    
  - name: Deploy War File
    get_url:
       url: http://35.154.221.163:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife1&p=war&v=LATEST
       dest: /var/lib/tomcat/webapps/gameoflife.war
  - name: Start Tomcat
    service:
      name: tomcat
      state: started  
